- hosts: centos
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: check apache 
    yum:
     name: httpd
     state: latest     
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  - name: delete var
    file:
      path: /var/www
      state: absent
  - name: clone repo
    git: 
      repo=https://github.com/Pwapou/blogtesting.git
      dest=/var/www
      version=HEAD
  - name: restart apache
    service:
      name: httpd
      state: restarted
 
